apiVersion: v1
kind: ConfigMap
metadata:
  name: faveo-env
  namespace: faveo-thetamilselvan
data:
  .env: |
    APP_NAME=Faveo:8a0c0be543c4ee86a23247f527c5e2cc
    APP_DEBUG=false
    APP_BUGSNAG=true
    APP_URL=https://faveo.thetamilselvan.in
    APP_KEY=base64:EVUC77pywUdjwqNClkmaKX3leeND2sX0qgRVZHegB8g=
    DB_TYPE=mysql
    DB_WRITE_HOST=
    DB_READ_HOST=
    DB_HOST="10.43.46.176"
    DB_PORT=""
    DB_DATABASE="faveo"
    DB_USERNAME="faveo"
    DB_PASSWORD="faveo"
    DB_ENGINE=InnoDB
    MAIL_MAILER=smtp
    MAIL_HOST=mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    CACHE_DRIVER=file
    SESSION_DRIVER=file
    SESSION_COOKIE_NAME=faveo_5441
    QUEUE_DRIVER=sync
    REDIS_HOST=faveo-redis
    REDIS_PORT=6379
    FCM_SERVER_KEY=AIzaSyBJNRvyub-_-DnOAiIJfuNOYMnffO2sfw4
    FCM_SENDER_ID=505298756081
    PROBE_PASS_PHRASE=fe2d31b0bac0793e9a96b688fc3cfb84
    REDIS_DATABASE=0
    BROADCAST_DRIVER=pusher
    LARAVEL_WEBSOCKETS_ENABLED=false
    LARAVEL_WEBSOCKETS_PORT=6001
    LARAVEL_WEBSOCKETS_HOST=127.0.0.1
    LARAVEL_WEBSOCKETS_SCHEME=http
    PUSHER_APP_ID=azGBkqKHjRDU2LXO
    PUSHER_APP_KEY=f07002f019b56975e21f59445f33d551
    PUSHER_APP_SECRET=b990532652dd1723dca468c9e2f73939
    PUSHER_APP_CLUSTER=mt1
    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
    SOCKET_CLIENT_SSL_ENFORCEMENT=false
    LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT=null
    LARAVEL_WEBSOCKETS_SSL_LOCAL_PK=null
    LARAVEL_WEBSOCKETS_SSL_PASSPHRASE=null
    DB_SSL_KEY=
    DB_SSL_CERT=
    DB_SSL_CA=
    DB_SSL_VERIFY_PEER_CERT=false
    SCOUT_DRIVER=database
    MEILISEARCH_HOST=
    MEILISEARCH_KEY=
    ALGOLIA_APP_ID=
    ALGOLIA_SECRET=
    DB_INSTALL=1
    APP_ENV=production

    JWT_SECRET=TS56h0o9v06NERr0ELYIQhpEuQzT6D4m3iYaC3VA0spqqyNj6PpRpFGFbIwUXn2u