apiVersion: v1
kind: Service
metadata:
  name: faveo-redis
  namespace: default
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faveo-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faveo-redis
  template:
    metadata:
      labels:
        app: faveo-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
